# Generated by Django 2.2 on 2019-04-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prod_name', models.CharField(max_length=128, verbose_name='Produkt')),
                ('Start_date', models.DateField(blank=True, null=True, verbose_name='Data rozpoczęcia wyświetlania')),
                ('Stop_date', models.DateField(blank=True, null=True, verbose_name='Data zakończnia wyświetlania')),
                ('Main_label', models.CharField(max_length=128, null=True, verbose_name='Główny label')),
                ('Second_label', models.CharField(blank=True, default=' ', max_length=72, null=True, verbose_name='Dodatkowy label')),
                ('Price_whole', models.IntegerField(blank=True, null=True, verbose_name='Cena całkowita')),
                ('Price_rest', models.IntegerField(blank=True, null=True, verbose_name='Reszta')),
                ('Product_weight', models.CharField(blank=True, default=' ', max_length=20, null=True, verbose_name='Gramatura')),
                ('Product_img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Zdjęcie produktu')),
                ('Type_slide', models.BooleanField(default=False, verbose_name='Slajd informacyjny')),
                ('Price_sep', models.CharField(blank=True, default=',', max_length=10, null=True, verbose_name='Separator ceny')),
                ('Gram_sep', models.CharField(blank=True, default='/', max_length=10, null=True, verbose_name='Separator gramatury')),
            ],
            options={
                'verbose_name': 'Promocja',
                'verbose_name_plural': 'Promocje',
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_sun', models.CharField(default='', max_length=255, verbose_name='Oznaczenie')),
                ('Type_mode_sun', models.BooleanField(default=False, verbose_name='Aktywność')),
                ('Type_info', models.CharField(blank=True, default='', max_length=255, verbose_name='Oznacznie')),
                ('Type_mode_info', models.BooleanField(default=False, verbose_name='Aktywność')),
                ('Type_mode_all', models.BooleanField(default=False, verbose_name='Aktywność')),
            ],
            options={
                'verbose_name': 'Konfiguracja',
            },
        ),
    ]
