# Generated by Django 2.1.7 on 2019-02-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prom',
            name='Main_label',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='prom',
            name='Price_rest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prom',
            name='Price_whole',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prom',
            name='Product_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='prom',
            name='Second_label',
            field=models.CharField(max_length=72, null=True),
        ),
        migrations.AddField(
            model_name='prom',
            name='Start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prom',
            name='Stop_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
