# Generated by Django 2.1.7 on 2019-03-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190320_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prom',
            name='Price_sep',
            field=models.CharField(blank=True, default='/', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='prom',
            name='Type_slide',
            field=models.BooleanField(blank=True, null=True, verbose_name='Slajd informacyjny'),
        ),
    ]
