# Generated by Django 2.1.7 on 2019-03-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190328_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='Type_info',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Oznacznie'),
        ),
    ]
