# Generated by Django 2.1.7 on 2019-03-28 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190328_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='Type_all',
        ),
    ]
