# Generated by Django 2.1.7 on 2019-03-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_siteconfiguration_type_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prom',
            name='Type_slide',
            field=models.BooleanField(default=False, verbose_name='Slajd informacyjny'),
        ),
    ]
