# Generated by Django 2.1.7 on 2019-03-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190306_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='prom',
            name='Product_weight',
            field=models.CharField(blank=True, default=' ', max_length=128, null=True, verbose_name='Gramatura'),
        ),
        migrations.AlterField(
            model_name='prom',
            name='Second_label',
            field=models.CharField(blank=True, default=' ', max_length=72, null=True, verbose_name='Dodatkowy label'),
        ),
    ]
