# Generated by Django 2.1.7 on 2019-03-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190306_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='prom',
            name='Price_sep',
            field=models.TextField(blank=True, default='/', null=True),
        ),
        migrations.AddField(
            model_name='prom',
            name='Type_slide',
            field=models.BooleanField(blank=True, default='', null=True, verbose_name='Slajd informacyjny'),
        ),
    ]
