# Generated by Django 2.1.7 on 2019-03-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190320_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='prom',
            name='Gram_sep',
            field=models.CharField(blank=True, default='/', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prom',
            name='Price_sep',
            field=models.CharField(blank=True, default=',', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prom',
            name='Product_weight',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True, verbose_name='Gramatura'),
        ),
    ]
