# Generated by Django 2.1.7 on 2019-03-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190320_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Site Name', max_length=255)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.AlterField(
            model_name='prom',
            name='Gram_sep',
            field=models.CharField(blank=True, default='/', max_length=10, null=True, verbose_name='Separator gramatury'),
        ),
        migrations.AlterField(
            model_name='prom',
            name='Price_sep',
            field=models.CharField(blank=True, default=',', max_length=10, null=True, verbose_name='Separator ceny'),
        ),
    ]
