# Generated by Django 2.1.7 on 2019-03-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190328_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': 'Konfiguracja'},
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='maintenance_mode',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='site_name',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='Type_all',
            field=models.CharField(default='', max_length=255, verbose_name='Oznaczenie'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='Type_info',
            field=models.CharField(default='', max_length=255, verbose_name='Oznacznie'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='Type_mode_all',
            field=models.BooleanField(default=False, verbose_name='Aktywność'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='Type_mode_info',
            field=models.BooleanField(default=False, verbose_name='Aktywność'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='Type_mode_sun',
            field=models.BooleanField(default=False, verbose_name='Aktywność'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='Type_sun',
            field=models.CharField(default='', max_length=255, verbose_name='Oznaczenie'),
        ),
    ]
