# Generated by Django 2.1.7 on 2019-03-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190328_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='Type_info',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Oznacznie'),
        ),
    ]
